# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/envs/r_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/envs/r_env/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/envs/r_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/envs/r_env/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/envs/r_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/envs/r_env/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/envs/r_env/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/envs/r_env/include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
z = np.zeros(10)

In [6]:
print('%d bytes' % (z.size * z.itemsize))

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [8]:
x1 = np.arange(1, 10).reshape(3, 3)
print(x1)
x2 = np.arange(1, 4)
print(x2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [9]:
np.add(x1, x2)

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [10]:
x1 + x2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
z = np.arange(10)
print(z)
z = z[::-1]
print(z)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
matrix = np.arange(9).reshape(-1, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [16]:
z = np.array([1,2,0,0,4,0])
np.arange(len(z))[z != 0]

array([0, 1, 4])

In [17]:
np.nonzero([1,2,0,0,4,0])[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
answer(11)

Z = np.eye(3)
print(Z)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [20]:
np.random.random(size=(3,3,3))

array([[[0.71619607, 0.06596132, 0.41916701],
        [0.54435207, 0.50659113, 0.1230502 ],
        [0.11677516, 0.93108239, 0.52085806]],

       [[0.78933136, 0.36051681, 0.92868914],
        [0.52426453, 0.27778453, 0.48241875],
        [0.74546035, 0.7977276 , 0.80832079]],

       [[0.10485654, 0.82940552, 0.2664658 ],
        [0.83953681, 0.17605781, 0.45483627],
        [0.44709807, 0.2144054 , 0.9201463 ]]])

In [21]:
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
z = np.random.random(size=(10, 10))
print(np.max(z))
print(np.min(z))

0.9983221685690152
0.02769211073125366


In [23]:
z.min(), z.max()

(0.02769211073125366, 0.9983221685690152)

In [24]:
answer(13)

Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
np.random.seed(13)
np.mean(np.random.random(size=30))

0.5004323986271216

In [26]:
np.random.seed(13)
z = np.random.random(30)
z.mean()

0.5004323986271216

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [27]:
z = np.ones(9).reshape(3, 3)
z[1:-1, 1:-1] = 0

In [28]:
z

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [29]:
answer(16)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)


In [30]:
z = np.ones(shape=(5,5))
np.pad(z, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [31]:
z = np.ones(shape=(5,5))
np.pad(z, pad_width=3, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [32]:
0 * np.nan

nan

In [33]:
np.nan == np.nan

False

In [34]:
np.inf > np.nan

False

In [35]:
np.nan - np.nan

nan

In [36]:
np.nan in set([np.nan])

True

In [37]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [38]:
z = np.repeat(np.arange(5), 5).reshape(5, 5)

In [39]:
z

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [40]:
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [41]:
z = np.zeros((8, 8), dtype=int)
z[::2, 1::2] = 1
z[1::2, ::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?   (★☆☆)

In [42]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [43]:
z = np.ones((2, 2), dtype=int)
z[0, 0] = 0
z[1, 1] = 0
z

array([[0, 1],
       [1, 0]])

In [44]:
np.tile(z, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [45]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [46]:
z = np.random.randint(9, size=(5,5))
(z - z.mean()) / z.std()

array([[ 0.91666667, -0.33333333, -0.33333333,  0.91666667,  0.91666667],
       [-0.33333333, -1.58333333,  1.33333333,  1.75      ,  0.91666667],
       [ 0.08333333, -0.33333333,  0.5       , -1.58333333,  0.5       ],
       [ 0.08333333, -0.33333333, -0.75      , -1.16666667,  1.75      ],
       [ 0.5       ,  0.5       , -1.16666667, -1.16666667, -1.58333333]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [47]:
answer(23)

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [48]:
np.random.seed(13)
a = np.random.randint(9, size=(5, 3))
b = np.random.randint(9, size=(3, 2))

In [49]:
np.dot(a, b)

array([[10,  6],
       [46, 36],
       [41, 33],
       [64, 51],
       [13, 12]])

In [50]:
a @ b

array([[10,  6],
       [46, 36],
       [41, 33],
       [64, 51],
       [13, 12]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [51]:
z = np.arange(11)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
z[(z > 3) & (z < 8)]

array([4, 5, 6, 7])

In [53]:
z[(z > 3) & (z < 8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [54]:
sum(list(range(5)), 4)

14

In [55]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [56]:
answer(27)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [57]:
np.array(0) / np.array(0)

/opt/anaconda3/envs/r_env/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [58]:
np.array(0) // np.array(0)

/opt/anaconda3/envs/r_env/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [59]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [60]:
answer(29)

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))


In [61]:
z = np.random.uniform(-10, 10, 10)
z

array([-3.0483757 , -9.8117446 , -2.83332435,  8.98188363, -5.64201982,
       -3.61217267,  8.35544772, -9.36192667, -8.69830926,  2.59657998])

In [62]:
np.copysign(np.ceil(np.abs(z)), z)

array([ -4., -10.,  -3.,   9.,  -6.,  -4.,   9., -10.,  -9.,   3.])

#### 30. How to find common values between two arrays? (★☆☆)

In [63]:
np.random.seed(13)
a = np.random.randint(20, size=15)
b = np.random.randint(10, 30, size=15)

In [64]:
np.intersect1d(a, b)

array([10, 11, 12, 13, 18])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [65]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [66]:
np.sqrt(-1) == np.emath.sqrt(-1)

/opt/anaconda3/envs/r_env/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [67]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [68]:
yesterday, today, tomorrow

(numpy.datetime64('2020-05-16'),
 numpy.datetime64('2020-05-17'),
 numpy.datetime64('2020-05-18'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [69]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [70]:
answer(34)

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [71]:
answer(35)

A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [72]:
z = np.random.uniform(0,10,10)
z

array([4.70137857, 6.24432527, 6.89778139, 2.88766033, 0.5283656 ,
       7.87670216, 5.25843857, 1.96831607, 5.95203941, 5.43083485])

In [73]:
z - z % 1

array([4., 6., 6., 2., 0., 7., 5., 1., 5., 5.])

In [74]:
z // 1

array([4., 6., 6., 2., 0., 7., 5., 1., 5., 5.])

In [75]:
np.floor(z)

array([4., 6., 6., 2., 0., 7., 5., 1., 5., 5.])

In [76]:
z.astype(int)

array([4, 6, 6, 2, 0, 7, 5, 1, 5, 5])

In [77]:
np.trunc(z)

array([4., 6., 6., 2., 0., 7., 5., 1., 5., 5.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [78]:
np.repeat(np.arange(5), 5).reshape(5, 5, order='F')

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [79]:
z = np.zeros((5,5))
z += np.arange(5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [80]:
def generate():
    for x in range(10):
        yield x

In [81]:
np.fromiter(generate(), dtype=float, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [82]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [83]:
z = np.random.randint(10, size=10)
print(z)
z.sort()
z

[6 6 3 0 7 8 6 4 3 5]


array([0, 3, 3, 4, 5, 6, 6, 6, 7, 8])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [84]:
answer(41)

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [87]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

In [88]:
np.allclose(A,B)

False

In [90]:
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [93]:
z = np.random.randint(20, size=10)
print(*z)
z[np.argmax(z)] = 0
z

4 6 13 19 11 3 16 4 9 18


array([ 4,  6, 13,  0, 11,  3, 16,  4,  9, 18])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [106]:
z = np.arange(9).reshape(3, 3)
for idx, val in np.ndenumerate(z):
    print(idx, val)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [111]:
p = int(input())

z = np.random.randint(20, size=p).reshape(-1, 3)
z

6


array([[ 3,  5, 19],
       [17, 17, 13]])

In [112]:
answer(57)

# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


In [120]:
n = 10
p = 3
z = np.zeros((n, n))
np.put(z, np.random.choice(range(n*n), p, replace=False), 1)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [121]:
n = 10
p = 3
z = np.zeros((n, n))
np.put(z, 10, 100)
z

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [144]:
np.random.seed(53)
z = np.random.randint(1, 10, size=16).reshape(4, 4)
z - z.mean(axis=1, keepdims=True)

array([[ 0.  ,  0.  ,  1.  , -1.  ],
       [-3.75,  4.25,  1.25, -1.75],
       [-1.  , -2.  ,  1.  ,  2.  ],
       [ 3.  , -1.  ,  2.  , -4.  ]])

#### 59. How to sort an array by the nth column? (★★☆)

In [166]:
np.random.seed(53)
z = np.random.randint(0, 15, (4, 4))
z

array([[ 9, 13,  5,  5],
       [11, 13,  6,  4],
       [ 0,  8, 10, 12],
       [ 9, 10,  5,  2]])

In [167]:
z[z[:, 1].argsort()]


array([[ 0,  8, 10, 12],
       [ 9, 10,  5,  2],
       [ 9, 13,  5,  5],
       [11, 13,  6,  4]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

__101. How to create a boolean array?__

In [171]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [172]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

102.

In [176]:
x = np.arange(10)
x[x % 2 != 0]

array([1, 3, 5, 7, 9])

103.

In [182]:
x = np.arange(10)
x[x % 2 != 0] = -1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

104.

In [184]:
x = np.arange(10)
print(np.where(x % 2 == 0, x, -1))
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [185]:
x = np.arange(10)
print(np.where(x % 2 == 1, -1, x))
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


105.

In [186]:
x = np.arange(10)
x.reshape(2,-1) # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

106.

In [192]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [194]:
np.concatenate((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [197]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [191]:
np.repeat(1, 10).reshape(2, -1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

107.

In [198]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [199]:
np.concatenate((a,b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [200]:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

108.

In [201]:
a = np.arange(1, 4)
a

array([1, 2, 3])

In [202]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [206]:
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [207]:
np.hstack((np.repeat(a, 3), np.tile(a, 3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

109.

In [208]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [209]:
np.intersect1d(a, b)

array([2, 4])

110.

In [210]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [214]:
a[~(a == np.intersect1d(a, b))]

array([1, 2, 3, 4])

In [215]:
# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 2, 3, 4])

111.

In [216]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [219]:
np.where(a == b)[0]

array([1, 3, 5, 7])

112.

In [220]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [226]:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [229]:
np.where((a >= 5) & (a <= 10))[0]

array([1, 3, 4])

In [ ]:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

In [233]:
index = np.where(np.logical_and(a >= 5, a <= 10))[0]
a[index]

array([ 6,  9, 10])

113.

In [234]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

In [235]:
pair_max = np.vectorize(maxx, otypes=[float])
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

114.

In [243]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [244]:
a = z[:, 1].copy()
b = z[:, 2].copy()

z[:, 1], z[:, 2] = b, a
z

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [245]:
# or
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [246]:
z[:, [0, 2, 1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

115.

In [247]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [248]:
z[[0,2,1],:]

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

116.

In [249]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [251]:
z[::-1, :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

117.

In [252]:
rand_arr = np.random.random([5,3])

In [253]:
np.set_printoptions(precision=3)

In [254]:
rand_arr

array([[0.348, 0.134, 0.26 ],
       [0.048, 0.394, 0.372],
       [0.557, 0.897, 0.167],
       [0.407, 0.652, 0.568],
       [0.567, 0.524, 0.608]])

118.

In [255]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [258]:
np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

119.

In [259]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

120.

In [264]:
np.set_printoptions(threshold=100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])